# -*- coding: utf-8 -*-

'''Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. 
The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8.
However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk,
for which their sum and difference are pentagonal
and D = |Pk − Pj| is minimised; what is the value of D?
'''
import time
T1=time.time()

N=10000
Pentagonales ={n:n*(3*n-1)/2 for n in xrange(2*N)}
PentagonalSet = set([n*(3*n-1)/2 for n in xrange(2*N)])
T2=time.time()

difminima=Pentagonales[N]
for a in xrange(1,N-1):
    for b in xrange(a+1,N):
        suma=Pentagonales[a]+Pentagonales[b]
        resta = Pentagonales[b]-Pentagonales[a]
        if (suma in PentagonalSet) and (resta in PentagonalSet):
            if resta<difminima:
                difminima=resta
                print "|P(%d)-P(%d)|=|%d-%d|=%d" % (b, a,Pentagonales[b],Pentagonales[a],resta)

T3=time.time()
print (T3-T1,T3-T2)