# -*- coding: utf-8 -*-
'''Problem 61

Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:

Triangle	 	P3,n=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Square	 	P4,n=n2	 	1, 4, 9, 16, 25, ...
Pentagonal	 	P5,n=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	P6,n=n(2n−1)	 	1, 6, 15, 28, 45, ...
Heptagonal	 	P7,n=n(5n−3)/2	 	1, 7, 18, 34, 55, ...
Octagonal	 	P8,n=n(3n−2)	 	1, 8, 21, 40, 65, ...
The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.

The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), is represented by a different number in the set.
This is the only set of 4-digit numbers with this property.
Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.
'''
from aritmetica import digitos

TRIANGS = [n*(n+1)/2 for n in range(44,141)]
CUADS = [n*n for n in range(31,101)]
PENTAS = [n*(3*n-1)/2 for n in range(25,82)]
HEXAS = [n*(2*n-1) for n in range(22,71)]
HEPTAS = [n*(5*n-3)/2 for n in range(20,64)]
OCTAS = [n*(3*n-2) for n in range(18,59)]

DigTriangs = {tuple(digitos(a)) for a in TRIANGS}
DigCuads = {tuple(digitos(a)) for a in CUADS}
DigPentas = {tuple(digitos(a)) for a in PENTAS}
DigHexas = {tuple(digitos(a)) for a in HEXAS}
DigHeptas = {tuple(digitos(a)) for a in HEPTAS}
DigOctas = {tuple(digitos(a)) for a in OCTAS}

def inicio(p):
    return (p[0],p[1])

def final(p):
    return (p[2],p[3])
    
def Search(p,listas, chain):
    print "trying:", p, len(listas), chain
    '''Determina si p puede continuar con algun término en "listas"'''
    if len(listas)<1:
        print "ACABAMOS", chain
        return []

    par = final(p)
    for L in listas:
        candidatos = [q for q in L if inicio(q) == par]
        if len(candidatos)>0:
            newlistas = listas[:]
            newlistas = newlistas.remove(L)
            print "\t"*len(chain),candidatos
            for c in candidatos:
                Search(c,newlistas,chain+[c])

			

p=(1,4,0,8)
LISTAS=[DigHeptas,DigHexas, DigPentas, DigCuads,DigTriangs]
CHAIN=[p]
Search(p, LISTAS, CHAIN)
